global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy-exporter:9101']
  - job_name: 'varnish'
    static_configs:
      - targets: ['varnish:9131']
  - job_name: 'docker'
    static_configs:
      - targets: ['192.168.10.1:9323']