x-common: &common
  networks:
    - fluentd-net
  logging:
    driver: local

services:
  fluentd:
    build:
      context: ${PWD}/context/fluentd
      dockerfile: ${PWD}/dockerfiles/Dockerfile-fluentd
    user: root:root
    volumes:
      - /var/lib/docker/containers:/mnt/docker-containers:ro
      - /tmp/fluentd-out:/mnt/output:rw
      - $PWD/context/fluentd/fluentd.conf:/fluentd/etc/fluent.conf
    <<: *common
  
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${PWD}/context/loki/loki.yaml:/etc/loki/local-config.yaml:ro
    networks:
      - fluentd-net
    <<: *common
  
  grafana:
    # Grafana image tag: 8.1.2 linux/amd64
    image: grafana/grafana@sha256:6bda2af009a4d3dd9d6dee3ef0c736ee3ab0a406d2f78fc93aeb5148a2e4219a
    ports: 
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    <<: *common

networks:
  fluentd-net: {}

volumes:
  grafana-storage: {}