x-common: &common
  restart: unless-stopped
  logging:
    options:
      tag: "{{.Name}}"

x-wp-common: &wp-common
  <<: *common
  networks:
    - wpnet
  

x-fluentd-common: &fd-common
  <<: *common
  networks:
    - fluentd-net

services:
  wpfront:
    # Wordpress image tag: 5.8.0-apache
    # image: wordpress@sha256:865ea4e55495630ae167c2240f6c9969e2fd185e2990c5edfac0914ce513b0cb
    build:
      context: ${PWD}/context/wordpress
      dockerfile: ${PWD}/dockerfiles/Dockerfile-wordpress
    depends_on: 
      - db
      - haproxy
      - varnish
    env_file:
      - wp.env
    read_only: yes
    user: "www-data:www-data"
    volumes: 
      - wp-content-root:/var/www/html/wordpress/wp-content
      - /tmp
      - /run/lock/apache2
      - /run/apache2
      - ${PWD}/context/wordpress/document-root/healthprobe.php:/var/www/html/wordpress/healthprobe.php:ro
      - ${PWD}/context/wordpress/document-root/wp-config.php:/var/www/html/wordpress/wp-config.php:ro
    deploy:
      mode: replicated
      replicas: 2
    <<: *wp-common

  db:
    image: percona@sha256:5bc1c13c8f4adfd76ceaac425877e2de2fcd9c33ab685c639e55b23e97eb0c0a
    environment: 
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wpTest2021!
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: zaq1@WSXcde3
    volumes:
      - wp-db-root:/var/lib/mysql
      - wp-db-log-root:/var/log/mysql
      - ${PWD}/context/mysql:/docker-entrypoint-initdb.d/:ro
    <<: *wp-common

  haproxy:
    build:
      context: ${PWD}/context/haproxy
      dockerfile: ${PWD}/dockerfiles/Dockerfile-haproxy
    ports:
      - 80:80
      - 443:443
      - 55666:5666
    volumes:
      - ${PWD}/context/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ${PWD}/context/haproxy/cert.pem:/etc/ssl/certs/test/cert.pem:ro
    depends_on: 
      - db
    <<: *wp-common

  varnish:
    build: 
      context: ${PWD}/context/varnish
      dockerfile: ${PWD}/dockerfiles/Dockerfile-varnish-multistage
    depends_on: 
      - haproxy
    ports:
      - 8080:80
    env_file:
      - varnish.env
    volumes:
      - ${PWD}/context/varnish/default.vcl:/etc/varnish/default.vcl:ro
    tmpfs: /var/lib/varnish:exec
    <<: *wp-common
  
  fluentd:
    build:
      context: ${PWD}/context/fluentd
      dockerfile: ${PWD}/dockerfiles/Dockerfile-fluentd
    user: root:root
    volumes:
      - /var/lib/docker/containers:/mnt/docker-containers:ro
      - /var/lib/docker/volumes/wp-docker_wp-db-root/_data:/mnt/mysql-data:ro
      - /tmp/fluentd-out:/mnt/output:rw
      - $PWD/context/fluentd/fluentd.conf:/fluentd/etc/fluent.conf
    logging:
      driver: local
    <<: *fd-common
  
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${PWD}/context/loki/loki.yaml:/etc/loki/local-config.yaml:ro
    <<: *fd-common
  
  grafana:
    # Grafana image tag: 8.1.2 linux/amd64
    image: grafana/grafana@sha256:6bda2af009a4d3dd9d6dee3ef0c736ee3ab0a406d2f78fc93aeb5148a2e4219a
    ports: 
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    <<: *fd-common


volumes:
  wp-db-root: {}
  wp-db-log-root: {}
  wp-content-root: {}
  grafana-storage: {}

networks:
  wpnet:
    ipam:
      config:
        - subnet: "192.168.10.0/24"
  fluentd-net: {}
