{
 "title": "Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Avg no. of requests per container",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (container_id) (\n  rate(\n    {source=\"docker\"}\n    | logfmt\n    | data_status_code > 0 or data_status > 0\n    | __error__ = \"\" [1m]\n  )\n)"
    }
   ]
  },
  {
   "title": "Current data throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (data_http_host) (\n  sum_over_time(\n    {source=\"docker\"}\n    | logfmt\n    | data_http_host != \"\"\n    | __error__ = \"\"\n    | unwrap data_bytes [1s]\n  )\n)"
    }
   ]
  },
  {
   "title": "Total Varnish requests by handling",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (data_handling) (\n  count_over_time(\n    {source=\"docker\"}\n    | logfmt\n    | data_handling != \"\"\n    | __error__ = \"\" [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Total Varnish requests by response code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (data_status_code) (\n  count_over_time(\n    {source=\"docker\",container_id=~\".*_varnish_.+\"}\n    | logfmt\n    | data_status_code > 0\n    | __error__ = \"\" [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (data_http_host) (\n  avg_over_time(\n    {source=\"docker\",container_id=~\".*_varnish_.+\"}\n    | logfmt\n    | data_duration_usec != \"\"\n    | data_duration_usec > 0\n    | unwrap data_duration_usec\n    | __error__ = \"\" [$__range]\n  )\n)"
    }
   ]
  }
 ]
}