{
 "title": "Apache details",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Most requested resources",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10, \n  sum (\n    count_over_time(\n      {source=\"docker\",container_id=~\".*_wpfront_.*\"}\n      | logfmt\n      | data_request != \"\"\n      | __error__ = \"\" [$__range]\n    )\n  ) by (data_host,data_request)\n)"
    }
   ]
  },
  {
   "title": "Requests with 4xx response",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (\n  count_over_time(\n    {source=\"docker\", container_id=~\".*_wpfront_.*\"}\n    | logfmt\n    | data_status >= 400 and data_status < 500\n    | __error__ = \"\" [$__range]\n  )\n) by (data_host, data_request)"
    }
   ]
  },
  {
   "title": "Avg response time per host",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (\n  sum_over_time(\n    {source=\"docker\", container_id=~\".*_wpfront_.*\"}\n    | logfmt\n    | unwrap data_time_taken_ms\n    | __error__ = \"\" [$__range]\n  )\n) by (data_host)"
    }
   ]
  },
  {
   "title": "Requests with 5xx response",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum (\n  count_over_time(\n    {source=\"docker\", container_id=~\".*_wpfront_.*\"}\n    | logfmt\n    | data_status >= 500\n    | __error__ = \"\" [$__range]\n  )\n) by (data_host, data_request)"
    }
   ]
  },
  {
   "title": "Total Apache requests per method",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  count_over_time (\n    {source=\"docker\", container_id=~\".*_wpfront_.*\"}\n    | logfmt\n    | data_method != \"\"\n    | __error__ = \"\" [$__range]\n  )\n) by (data_method)"
    }
   ]
  },
  {
   "title": "Total Apache requests by response code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  count_over_time(\n    {source=\"docker\", container_id=~\".*_wpfront_.*\"}\n    | logfmt\n    | data_status > 0\n    | __error__ = \"\" [$__range]\n  )\n) by (data_status)"
    }
   ]
  }
 ]
}