{
 "title": "Varnish details",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Varnish requests by handling",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (data_handling) (\n  count_over_time(\n    {source=\"docker\"}\n    | logfmt\n    | data_handling != \"\"\n    | __error__ = \"\" [$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (data_hit_miss)(count_over_time (\n      {source=\"docker\", container_id=~\".*_varnish_.*\"}\n      | logfmt\n      | data_hit_miss != \"\"\n      | __error__ = \"\"  [$__range]\n))"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg (\n  avg_over_time(\n    {source=\"docker\", container_id=~\".*_varnish_.*\"}\n    | logfmt\n    | unwrap data_duration_usec\n    | __error__ = \"\" [$__range]\n  )\n) by (data_http_host)"
    }
   ]
  }
 ]
}