{
 "title": "HAProxy Details",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Termination state overview",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  count_over_time(\n    {source=\"docker\", container_id=~\".*_haproxy_.*\"}\n    | logfmt\n    | data_termination_state != \"\"\n    | __error__ = \"\" [$__range]\n  )\n) by (data_termination_state)"
    }
   ]
  },
  {
   "title": "Backend queue length (rolling avg, 1min)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (\n  avg_over_time(\n    {source=\"docker\", container_id=~\".*_haproxy_.*\"}\n    | logfmt\n    | unwrap data_backend_queue\n    | __error__ = \"\" [1m]\n  )\n) by (data_backend_name)"
    }
   ]
  },
  {
   "title": "Frontend connections (rolling avg, 1 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum (\n  avg_over_time(\n    {source=\"docker\", container_id=~\".*_haproxy_.*\"}\n    | logfmt\n    | unwrap data_feconn\n    | __error__ = \"\" [1m]\n  )\n) by (data_frontend_name_transport)"
    }
   ]
  },
  {
   "title": "Backend connections (rolling avg, 1 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum (\n  avg_over_time(\n    {source=\"docker\", container_id=~\".*_haproxy_.*\"}\n    | logfmt\n    | unwrap data_beconn\n    | __error__ = \"\" [1m]\n  )\n) by (data_backend_name)"
    }
   ]
  }
 ]
}