x-common: &common
  restart: unless-stopped
  logging:
    options:
      tag: "{{.Name}}"
  
x-fluentd-common: &fd-common
  <<: *common
  networks:
    - fluentd-net

services:

  prometheus:
    image: prom/prometheus:v2.29.2
    hostname: prometheus
    volumes:
      - ${PWD}/../context/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090
    <<: *fd-common
    
  loki:
    image: grafana/loki:2.3.0
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${PWD}/../context/loki/loki.yaml:/etc/loki/local-config.yaml:ro
    <<: *fd-common
  
  grafana:
    # Grafana image tag: 8.1.2 linux/amd64
    image: grafana/grafana@sha256:6bda2af009a4d3dd9d6dee3ef0c736ee3ab0a406d2f78fc93aeb5148a2e4219a
    ports: 
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    <<: *fd-common


volumes:
  grafana-storage: {}

networks:
  wpnet: 
    external: true
  fluentd-net: 
    name: fluentd-net
